title: Didier Neuenschwander
email: neuenschwander.didier@gmail.com

description: "Robotics  Engineer (EPFL MSc) â€” 3D Vision, Deep Learning, ROS2."

github_username: DidierNe
minimal_mistakes_skin: dark
search: true

remote_theme: "mmistakes/minimal-mistakes@4.27.1"

markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Zurich

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:path/

author:
  name   : "Didier Neuenschwander"
  avatar : "/assets/images/profile.jpg"
  bio: "Robotics & Computer Vision Engineer | 3D Vision, Deep Learning, ROS2 | Medical & Industrial Robotics."
  location: "Switzerland"
  links:
    - label: "CV"
      icon: "fas fa-fw fa-file-alt"
      url: "/assets/CV_Didier_fr_feb.pdf"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/didier-neuenschwander-501a15291/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DidierNe"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:neuenschwander.didier@gmail.com"

footer:
  links:
    - label: "CV"
      icon: "fas fa-fw fa-file-alt"
      url: "/assets/CV_DN_2025_june.pdf"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/didier-neuenschwander-501a15291/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DidierNe"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:neuenschwander.didier@gmail.com"

exclude:
  - _pages/category-archive.md
  - _pages/tag-archive.md
  - _pages/year-archive.md
  - _posts

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

nav:
  - title: "About"
    url: /about/
